### ISSUE TITLE
Endwalker Update?

### ISSUE THREAD

**Issue by soonerrob** [Caraxi/PartyListLayout#13]
Is this plugin still being supported?

**Comment by bladehawkz** [comment]
The author is working on his main plugin (SimpleTweaks), and much more important overarching Dalamud stuff. 

I expect the plugin to only be updated after everything else is stable, _at the earliest_, and perhaps never. It's a lot of work maintaining plugins.

**Comment by VieLassiel** [comment]
I'm also waiting for this plugin to be updated and hope that the author finds time out of their busy schedule to do so.

Simple Tweaks is a lot more important and I'm grateful they kept it up to date, so thanks for that, just hopefully this plugin will get a little love too.

Eitherway, keep up the good work and thank you for your time. :)
