### ISSUE TITLE
[Feature Request] Add alpha/transparency option to party BG 

### ISSUE THREAD

**Issue by gucciBane** [Caraxi/PartyListLayout#19]
I'd like to use black and just make it less opaque. The closest I can get atm is a lighter grey, which looks washed out on top of darker backdrops.

Thanks

**Comment by Caraxi** [comment]
does it not already have alpha in the colour?

**Comment by gucciBane** [comment]
Not that I'm seeing

https://user-images.githubusercontent.com/49180180/152454147-074808ff-ca5e-4786-8e14-9ff29dc7e760.mp4

.

**Comment by Caraxi** [comment]
Added with 0.3.3
