### ISSUE TITLE
[Bug] Chocobo timer sometimes randomly decides that I'm in a 8-man party

### ISSUE THREAD

**Issue by CaspianRoach** [Caraxi/PartyListLayout#21]
![image](https://user-images.githubusercontent.com/7204157/154411290-e68fe204-f165-4920-96f0-1d6fee3c1c8d.png)
(timer icon is turned off)

Sometimes it appears right where it should, sometimes it appears as if I have 8 players in my party. The position is only slightly Y-adjusted to fit with the #2 spot of the party frames, but this has happened to me when the position was (0; 0), too. Not a slightest idea what might be causing this.

Edit: Slight correction, the UI actually doesn't fit with party member #9 either, maybe that can help debug?
![image](https://user-images.githubusercontent.com/7204157/154417397-86cd4eb3-c6ca-484f-9ba4-b47573e7ba2e.png)

(it was previously aligned to fit snugle next to chocobo healthbar, when the timer was at the correct #2 spot)

here are the position settings for both screenshots: 
![image](https://user-images.githubusercontent.com/7204157/154417949-0d47aa71-71df-432b-af8d-5df13916d88c.png)

**Comment by Imaginary-Narwhal** [comment]
I am having an identical issue. The timer sits in the same place where the end of the party list would be.

**Comment by CaspianRoach** [comment]
Fixed in 0.3.3.0. Thanks!
