### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Kwehh13** [Caraxi/PartyListLayout#26]
Wondering when this will be updated for 6.1

**Comment by ryankhart** [comment]
I've tried to convert it to 6.1 on my own fork, using the trivial methods that usually work with other plugins, but this plugin, after updating it to the Dalamud Packager 2.1.6 (which I presume is API 6 made for patch 6.1) the plugin crashes the game leaving a not-so-helpful-to-me error message in the log.

I'm looking forward to learning how this kind of issue may be resolved so I can help contribute in the future.

**Comment by Werns** [comment]
Bump on this. Loved this layout way more than vanilla.

**Comment by Caraxi** [comment]
if I have time, I'll do it over this weekend

**Comment by Caraxi** [comment]
It is done

**Comment by ryankhart** [comment]
Woo! Much appreciated! Both as a user of this plugin and developer wanting to learn.

**Comment by DNNYVST** [comment]
<3

**Comment by ryankhart** [comment]
Ok, I've tested it out, and so far, it has NOT crashed my game like I had reported before. I thought this was worth coming back to clarify in case you had put it a testing build based on my report.
