### ISSUE TITLE
Not Compatible with latest version of FFXIV

### ISSUE THREAD

**Issue by Jwidea** [Caraxi/PartyListLayout#31]
I really love your plugin, but by any chance there will be further update for this?

**Comment by thoccavelli** [comment]
> I really love your plugin, but by any chance there will be further update for this?

Agree. I love healing & raiding with Caraxi's PartyListLayout. The HUD is so much cleaner with it. This great addon should be promoted beyond "testing" to the main Dalamud Plugins lineup.  Thank you, Caraxi!
