### ISSUE TITLE
Cast bar doesn't fill/animate

### ISSUE THREAD

**Issue by FrUct1s** [Caraxi/PartyListLayout#32]
![image](https://user-images.githubusercontent.com/58904408/187072495-94cc7f09-f6dc-4963-8e4d-1142e8735d2e.png)

**Comment by Caraxi** [comment]
will investigate

**Comment by CaspianRoach** [comment]
This has been happening to Trust and Chocobo cast bars for a while (#22), but now it also affects self and party.

**Comment by Caraxi** [comment]
Fixed in latest version
