### ISSUE TITLE
Party list not showing up

### ISSUE THREAD

**Issue by mikeysithu** [Caraxi/PartyListLayout#33]
Party list not showing up
![image](https://user-images.githubusercontent.com/2087576/187076080-9fd7e139-0506-43f3-a9d3-3529006d290a.png)
 
and when its off its back
![image](https://user-images.githubusercontent.com/2087576/187076097-a5e29704-de69-42f3-83ef-56966c6e8082.png)

**Comment by ZyRage** [comment]
It's the background option.
As soon as you turn off the background, everything vanishes

**Comment by mikeysithu** [comment]
> It's the background option. As soon as you turn off the background, everything vanishes

thank you

**Comment by ZyRage** [comment]
I would still let this issue be open, as the background should only turn off the background and not everything so it is a bug imo :D

**Comment by Zebouski** [comment]
yep @mikeysithu  please leave this back open so @Caraxi sees. 

I carried over my config from earlier to this new version, and was baffled about why the plugin "wasnt working" at all lol. my layout relies on the background being off to look good.
