### ISSUE TITLE
Party frame Backdrop

### ISSUE THREAD

**Issue by dansa** [Caraxi/PartyListLayout#5]
I assume its disabled for a reason when you enable the plugin, but it would be nice to have an option to have a configurable backdrop to the party list as it increases readability of some things.

Default backdrop for reference
![image](https://user-images.githubusercontent.com/5786317/131264513-1b59a9e6-9edf-4dcf-9fa9-684deb359c9d.png)

**Comment by Caraxi** [comment]
I see about getting it back. it's disabled atm because it's one big sprite that gets more and more ugly the more I resize it. I'll see what I can do though
